// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAP-OL7wBxcWG-MsUjv2oV000iuXccy8wY',
    appId: '1:769344764627:web:fb1319539fc803c62af226',
    messagingSenderId: '769344764627',
    projectId: 'vehicle-damage-detection-e4db5',
    authDomain: 'vehicle-damage-detection-e4db5.firebaseapp.com',
    storageBucket: 'vehicle-damage-detection-e4db5.firebasestorage.app',
    measurementId: 'G-JYRQHYQLX3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsw-cmhh8wDuo245isJkU8dB-4bOCDzs4',
    appId: '1:769344764627:android:9be6ce11428906912af226',
    messagingSenderId: '769344764627',
    projectId: 'vehicle-damage-detection-e4db5',
    storageBucket: 'vehicle-damage-detection-e4db5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBygoNz44cLm4wlXbZDv6u_Us_jxQaaRCE',
    appId: '1:769344764627:ios:b41e29489d19813c2af226',
    messagingSenderId: '769344764627',
    projectId: 'vehicle-damage-detection-e4db5',
    storageBucket: 'vehicle-damage-detection-e4db5.firebasestorage.app',
    iosClientId: '769344764627-kggaf2ga8uivm5bkvsm2cmr4q5isifoe.apps.googleusercontent.com',
    iosBundleId: 'com.vehiclebuddy.vehicleHealthTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBygoNz44cLm4wlXbZDv6u_Us_jxQaaRCE',
    appId: '1:769344764627:ios:b41e29489d19813c2af226',
    messagingSenderId: '769344764627',
    projectId: 'vehicle-damage-detection-e4db5',
    storageBucket: 'vehicle-damage-detection-e4db5.firebasestorage.app',
    iosClientId: '769344764627-kggaf2ga8uivm5bkvsm2cmr4q5isifoe.apps.googleusercontent.com',
    iosBundleId: 'com.vehiclebuddy.vehicleHealthTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAP-OL7wBxcWG-MsUjv2oV000iuXccy8wY',
    appId: '1:769344764627:web:9774cdeb9ae320fc2af226',
    messagingSenderId: '769344764627',
    projectId: 'vehicle-damage-detection-e4db5',
    authDomain: 'vehicle-damage-detection-e4db5.firebaseapp.com',
    storageBucket: 'vehicle-damage-detection-e4db5.firebasestorage.app',
    measurementId: 'G-YX1VJE10L1',
  );
}
